#! /bin/bash
python run.py --experiment 'bert-base'
wandb sync --sync-all --clean
python run.py --experiment 'bert-large'
wandb sync --sync-all --clean
python run.py --experiment 'roberta-base'
wandb sync --sync-all --clean
python run.py --experiment 'roberta-large'
wandb sync --sync-all --clean
python run.py --experiment 'albert-base'
wandb sync --sync-all --clean
python run.py --experiment 'albert-large'
wandb sync --sync-all --clean
python run.py --experiment 'distilbert-base-uncased'
wandb sync --sync-all --clean
python run.py --experiment 'distilroberta'
wandb sync --sync-all --clean
python run.py --experiment 'distilbert-base-squad2'
wandb sync --sync-all --clean
python run.py --experiment 'roberta-base-squad2'
wandb sync --sync-all --clean
python run.py --experiment 'distilroberta-base-squad2'
wandb sync --sync-all --clean
python run.py --experiment 'bert-base-squad2'
wandb sync --sync-all --clean
python run.py --experiment 'albert-base-squad2'
wandb sync --sync-all --clean
