#! bin/bash
python run.py --experiment 'bert-base'
python run.py --experiment 'bert-large'
python run.py --experiment 'roberta-base'
python run.py --experiment 'roberta-large'
python run.py --experiment 'albert-base'
python run.py --experiment 'albert-large'
python run.py --experiment 'distilbert-base-uncased'
python run.py --experiment 'distilroberta'
python run.py --experiment 'distilbert-base-squad2'
python run.py --experiment 'roberta-base-squad2'
python run.py --experiment 'distilroberta-base-squad2'
python run.py --experiment 'bert-base-squad2'
python run.py --experiment 'albert-base-squad2'
