DEFAULT:
    model_name: bert-base-uncased
    data_source: scientsbank
    data_val_origin: answer
    learn_rate: 1.e-5
    max_epochs: 24
    num_labels: 2
    batch_size: 8
    train_percent: 100
    val_percent: 100
    num_labels: 2
    num_workers: 4
    group: group
    drop_last: False
    log: True
    name: null
    from_scratch: False
    max_patience: 5
    optimizer: Adam
    optimizer_kwargs: {}
    scheduler: linear_with_warmup
    scheduler_args:
      - 1024
      - 17000
    scheduler_kwargs: {}
