models:
  - bert-base
  - bert-large
  - roberta-base
  - roberta-large
  - albert-base
  - albert-large
  - distilbert-base
  - distilroberta
  - distilbert-base-squad2
  - roberta-base-squad2
  - distilroberta-base-squad2
  - bert-base-squad2
  - albert-base-squad2
