from_scratch:
  from_scratch: true

htune:
    group: htune
    max_epochs: 35
    max_patience: null
    optimizer: AdamW
    optimizer_kwargs:
        weight_decay: 1.e-5
    learn_rate: 1.e-5
    batch_size: 8
    scheduler: linear_with_warmup
