DATA:
    data_dir: data
    train_data_file: flat_semeval5way_train.csv
    val_data_file: flat_semeval5way_test.csv

---
 DEFAULT:
    model_name: bert-base-uncased
    data_source: scientsbank
    data_val_origin: answer
    learn_rate: 1.e-5
    max_epochs: 24
    num_labels: 2
    batch_size: 8
    train_percent: 100
    val_percent: 100
    num_labels: 2
    num_workers: 4
    group: ''
    drop_last: False
    log: True
    name: null
    from_scratch: False
    max_patience: 5
    optimizer: AdamW
    optimizer_kwargs:
        weight_decay: 1.e-5
    scheduler: linear_with_warmup
    scheduler_args:
      - 1024
      - 17000
    scheduler_kwargs: {}
    token_types: False

---
# models
bert-base:
    name: bert-base
    model_name: bert-base-uncased

bert-large:
    name: bert-large
    model_name: bert-large-uncased

roberta-base:
    name: roberta-base
    model_name: roberta-base

roberta-large:
    name: roberta-large
    model_name: roberta-large

albert-base:
    name: albert-base
    model_name: albert-base-v2

albert-large:
    name: albert-large
    model_name: albert-large-v2

distilbert-base:
    name: distilbert-base
    model_name: distilbert-base-uncased

distilroberta:
    name: distilroberta
    model_name: distilroberta-base

distilbert-base-squad2:
    name: distilbert-base-squad2
    model_name: twmkn9/distilbert-base-uncased-squad2

roberta-base-squad2:
    name: roberta-base-squad2
    model_name: deepset/roberta-base-squad2

distilroberta-base-squad2:
    name: distilroberta-base-squad2
    model_name: twmkn9/distilroberta-base-squad2

bert-base-squad2:
    name: bert-base-squad2
    model_name: twmkn9/bert-base-uncased-squad2

albert-base-squad2:
    name: albert-base-squad2
    model_name: twmkn9/albert-base-v2-squad2

---
# parameters
token_types:
  token_types: True
  group: token_types

from_scratch:
  from_scratch: true

beetle:
  data_source: beetle

scientsbank:
  data_source: scientsbank

no_max:
  max_patience: null
